### ISSUE TITLE
npm run create-cloudformation seems to ignore the REGION set in .env

### ISSUE THREAD

**Issue by kabo** [jimpick/lambda-comments#10]
In my `.env`:

```
REGION=ap-southeast-2
```

then I ran `npm run create-cloudformation`. But the cloudformation stack got created in us-west-2.

**Comment by bkruger99** [comment]
Looks like it's still not merged in ?   I checked master and the refactor branch..

**Comment by jimpick** [comment]
Oops, kabo closed the bug report in his branch -- I mistakenly thought the problem was resolved. But I see he made a commit in his tree, and didn't do a pull request. I'll merge it.
