### ISSUE TITLE
Use root akismet-api package

### ISSUE THREAD

**Issue by chrisfosterelli** [jimpick/lambda-comments#3]
Hey there, congrats on reaching the front page of HN!
A colleague pointed out that you're using a forked version of my [akismet-api] library, I'm glad it's useful for building this. I was curious about the changes and I noticed you just updated superagent.

I had an issue for that [here], but superagent changes the way it passes around errors in 1.0 so I had to do some additional testing to make sure everything was good. 

I just released a new version (2.1.0) that supports superagent 1.8.3, so you might want to consider using the root `akismet-api` package again! If you have any other suggestions for the library, feel free to [make an issue or pull request]!

[akismet-api]: https://www.npmjs.com/package/akismet-api
[here]: https://github.com/chrisfosterelli/akismet-api/issues/7
[make an issue or pull request]:https://github.com/chrisfosterelli/akismet-api/issues/new

**Comment by jimpick** [comment]
Thanks! I'll definitely test it out. Hopefully the webpack build issues have gone away.
